config/routes.rb
Uwbooks::Application.routes.draw do
  root :to => "books#index"

  resources :books do
    get :mine, :on => :collection, :as => :my
    put :remove, :on => :member
  end

  resource :users, :except => :destroy

  post '/login' => 'user_sessions#create'
  get '/login' => 'user_sessions#new', :as => :login
  get '/logout' => 'user_sessions#destroy', :as => :logout
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user

  validates_numericality_of :price
  validates_presence_of :author
  validates_presence_of :title

  validate :isbn_is_valid

  default_scope order('created_at DESC').where(:removed => false)

  def isbn_is_valid
    # TODO: actually check
    true
  end

  def owned_by(a_user)
    user == a_user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.require_password_confirmation = false
  end

  has_many :books, :dependent => :destroy

  accepts_nested_attributes_for :books
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session

  # fix due to rails3
  def to_key
      new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user_session, :current_user

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end


  def require_user
    unless current_user
      flash[:notice] = "You must be logged in to access this page"
      redirect_to root_path
      return false
    end
  end

  def require_no_user
    if current_user
      flash[:notice] = "You must be logged out to access this page"
      redirect_to root_path
      return false
    end
  end


end

app/controllers/base_controller.rb
class BaseController < InheritedResources::Base
end

app/controllers/books_controller.rb
class BooksController < BaseController
  actions :all, :except => :show

  respond_to :js, :only => [:index, :mine, :remove]

  before_filter :require_user, :only => [:edit, :update, :destroy, :mine]

  before_filter :ensure_book_is_mine, :only => [:edit, :update, :destroy]

  # CRUD actions

  def index
    @books = end_of_association_chain.includes(:user)
    # @books = @books.with_keywords(params[:search]) unless params[:search].blank?
    @books = @books.paginate(:page => params[:page])
  end

  def create
    @book = current_user.books.new(params[:book])
    create! { my_books_path }
  end

  def update
    update! { my_books_path }
  end

  def destroy
    destroy! { my_books_path }
  end

  # Custom actions

  def mine
    @books = end_of_association_chain
      .where(:user_id => current_user.id)
      .includes(:user)
      .paginate(:page => params[:page])
  end

  def remove
    Book.update(params[:id], :removed => true)

    respond_with do |format|
      format.html { redirect_to my_books_path }
      format.js { }
    end
  end

  # Methods

  # Filters

  def ensure_book_is_mine
    unless !current_user || resource.user == current_user
      flash[:notice] = "You must own the book"
      redirect_to my_books_path
      return false
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = 'Welcome back!'
      redirect_to my_books_path
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = 'Come back again!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  actions :new, :create, :edit, :update, :destroy

  before_filter :require_user, :only => [:update, :destroy]
  before_filter :require_no_user, :only => [:create]

  before_filter :switch_new_to_edit, :only => :new
  before_filter :switch_edit_to_new, :only => :edit

  # Actions

  def new
    @user = User.new
    @user.books.build

    new!
  end

  def create
    # try to authenticate the user
    user_session = UserSession.new(params[:user])
    if user_session.save
      @user = user_session.user

      @book = @user.books.new(params[:user][:books_attributes]['0'])
      if @book.save
        redirect_to my_books_path
      else
        render 'books/new'
      end
    else
      if User.find_by_email(params[:user][:email])
        @user = User.new(params[:user])
        @user.errors[:password] = 'is incorrect.'
        render :action => 'new'
      else
        # fall back to creating the user
        @user = User.new(params[:user])
        if @user.save
          UserMailer.signup(@user).deliver
          redirect_to my_books_path
        else
          render :action => 'new'
        end
      end
    end
  end

  # Filters

  def switch_new_to_edit
    if current_user
      redirect_to edit_users_path
      return false
    end
  end

  def switch_edit_to_new
    unless current_user
      redirect_to new_users_path
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/books/_book.html.erb
<div class='book' id='book_<%= book.id %>'>
  <% if current_user && book.owned_by(current_user) %>
  <div class='book_actions'>
    <%= link_to 'Edit', edit_book_path(book) %><br/>
    <%= link_to 'Remove', remove_book_path(book), :confirm => 'Are you sure?', :method => :put, :remote => true %>
  </div>
  <% end %>

  <span class='book_title'><%= book.title %></span> <span class='book_author'> - <%= book.author %></span>

  <br/>

  <%= number_to_currency book.price %><br/>
  <b>Course(s):</b> <%= book.course %><br/>
  <b>ISBN:</b> <%= book.isbn %>

  <div class='book_description'>
    <%= simple_format book.description %>
  </div>

  <div>
    <!-- image goes here -->
  </div>

</div>

app/views/books/_books.html.erb
<% @books.each do |book| %>
  <%= render book %>
<% end %>

app/views/books/_form.html.erb
<div class="field">
  <%= f.label :isbn %>
  <%= f.text_field :isbn, :id => 'books_isbn' %>
</div>
<div class="field">
  <%= f.label :price %>
  <%= f.text_field :price, :id => 'books_price' %>
</div>
<div class="field">
  <%= f.label :author %>
  <%= f.text_field :author, :id => 'books_author' %>
</div>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, :id => 'books_title' %>
</div>
<div class="field">
  <%= f.label :course %>
  <%= f.text_field :course, :id => 'books_course' %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description, :id => 'books_description' %>
</div>

<img id='thumb'></img>

app/views/books/edit.html.erb
<h1>Updating</h1>

<%= form_for @book do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <div class="actions">
    <%= f.submit "Save", :disable_with => 'Saving...' %>
  </div>
<% end %>

<%= link_to 'Back', my_books_path %>

app/views/books/index.html.erb
<%= content_for :js do %>
<script type="text/javascript" charset="utf-8">
  $.scroller();
</script>
<% end if @books.total_pages > 1 %>

<h2>All Books</h2>

<div id='books'>

<%= render :partial => 'books', :locals => {:collection => @books} %>

</div>

app/views/books/index.js.erb
<% unless @books.empty? %>
$('#books').append($('<%= escape_javascript(render :partial => 'books', :locals => {:collection => @books}) %>'));
$.scroller();
<% end %>

app/views/books/mine.html.erb
<%= content_for :js do %>
<script type="text/javascript" charset="utf-8">
  $.scroller();
</script>
<% end if @books.total_pages > 1 %>

<h2>My Books</h2>

<div id='books'>

<%= link_to 'Post more books', new_book_path %>

<%= render :partial => 'books', :locals => {:collection => @books} %>

</div>

app/views/books/mine.js.erb
<% unless @books.empty? %>
$('#books').append($('<%= escape_javascript(render :partial => 'books', :locals => {:collection => @books}) %>'));
$.scroller();
<% end %>

app/views/books/new.html.erb
<h1>Posting Books</h1>

<%= form_for @book do |f| %>
  <%= render :partial => 'books/form', :locals => {:f => f} %>
  <div class="actions">
    <%= f.submit "Post Book", :disable_with => 'Posting...' %>
  </div>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/remove.js.erb
$('#book_<%= params[:id] %>').slideUp(function(){$(this).remove()});

app/views/layouts/_login_form.html.erb
<div id='login_form'>
  <% if current_user %>
    Sup, <%= link_to current_user.email, my_books_path %>? <%= link_to 'logout', logout_path %>
  <% else %>
    <%= link_to 'post a book', new_users_path %>
    <%= link_to 'login', login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Uwbooks</title>
  <%= stylesheet_link_tag 'reset', 'text', '960', 'application' %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Philosopher&subset=latin' %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js' %>
  <%= javascript_include_tag 'jquery-1.4.4.min' if Rails.env.development? %>
  <%= javascript_include_tag 'rails', 'isbn', 'application' %>
  <%= yield :js %>
  <%= csrf_meta_tag %>
</head>
<body>
  <% if flash[:warning] or flash[:notice] %>
  <a href='#' id='notice_wrapper'>
    <div id='notice' <%= 'class="warning"' if flash[:warning] %>>
      <%= flash[:warning] || flash[:notice] %>
    </div>
    <script type="text/javascript">
      setTimeout("$('#notice_wrapper').slideUp();", 5000)
    </script>
  </a>
  <% end %>

  <div class='container_12'>
    <div id='header' class='grid_3 prefix_2'>
      <h1><a href='/'>UW books</a></h1>
    </div>
    <div class='grid_5'>
      <%= render :partial => 'layouts/login_form' %>
    </div>

    <div class='clear'></div>

    <div class='grid_8 prefix_2'>
      <div id='content'>
        <%= yield %>
      </div>
    </div>

    <div class='clear'></div>

    <div id='footer' class='grid12'>
      NR Aggressive Minimalist Style
      <br/>
      &#169; UW Books 2010
    </div>

    <div class='clear'></div>
  </div>

  <div id='pagination_wrapper'>
    <div id='pagination'>loading more books...</div>
  </div>

</body>
</html>

app/views/user_sessions/_form.html.erb
<% if @user_session.errors.any? %>
  <div id="error_explanation">
    <h2>We found <%= pluralize(@user_session.errors.count, "error") %>:</h2>

    <ul>
    <% @user_session.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :email %>
  <%= f.email_field :email %><br />
</div>

<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %><br />
</div>

<%= f.check_box :remember_me %><%= f.label :remember_me %><br />

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for :user_session, :url => login_path, :method => :create do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit "Login" %>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>We found <%= pluralize(@user.errors.count, "error") %>:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.fields_for :books do |f| %>
  <%= render :partial => 'books/form', :locals => {:f => f} %>
<% end %>
<div class="field">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="actions">
  <%= f.submit "Post Book", :disable_with => 'Posting...' %>
</div>

app/views/users/new.html.erb
<h1>Posting Books</h1>

<%= form_for @user do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<%= link_to 'Back', root_path %>